### ISSUE TITLE
Can't figure out how to get /dev/kfd to appear?

### ISSUE THREAD

**Issue by Wulfsta** [nixos-rocm/nixos-rocm#13]
I'm trying to get this working on a Radeon VII and have been running into a ton of problems. I cannot use a kernel below 4.20 and have yet to see anything related to kfd appear on my system (nothing in dmesg output as well). I have an old Haswell CPU, i7 4770, but that should support the atomics needed. Do I need to enable a kernel module or something? 

I've tried adding
```
services.udev = {
  extraRules = ''
    SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"
  '';
};
```
to my `/etc/nixos/configuration.nix` as can be found at https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Installation_Guide/Installation-Guide.rst, but that doesn't seem to help.

**Comment by acowley** [comment]
I'll paste here sections from my `configuration.nix` that may be relevant. I'll put a `...` for parts that I'm confident are not relevant to retain an approximation of syntactic validity of a nix file.

```
  services.udev.extraRules = ''
    SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"
    ...
  '';
```

```
boot.kernelModules = [ "8821ce" "amdgpu" "it87" "coretemp" "msr" ];
```
(of which I imagine only `"amdgpu"` is relevant here).

I also have,
```
services.xserver = {
...
videoDrivers = ["amdgpu"];
};
```
Finally, I have my user in the `"video"` group.

EDIT: I'm also not so sure about what one should expect from `dmesg`. I added that note in the README based on a bug report, but I'm not actually seeing anything in `dmesg` output myself at the moment, but ROCm software is working. What *is* working for me is `journalctl`,

```
$ journalctl -b | grep kfd
Mar 17 13:52:11 nixos-hp kernel: kfd kfd: Initialized module
Mar 17 13:52:11 nixos-hp kernel: kfd kfd: Allocated 3969056 bytes on gart
Mar 17 13:52:11 nixos-hp kernel: kfd kfd: added device 1002:67df
```

**Comment by Wulfsta** [comment]
I added my user to the video group, but the rest of my config has remained the same. I'm seeing no output related to kfd from journalctl. What kernel are you on? If it's less than 4.20 can you test with an update? 

Also, should I be enabling `hardware.opengl.driSupport` or `hardware.opengl.driSupport32Bit`?

**Comment by Wulfsta** [comment]
Whoops hit the wrong button!

**Comment by acowley** [comment]
I tried building with kernel 5.0.2, and also did not have any kfd appear. I can't look into it right now, but we'll have to dig around upstream to see if others are having issues. ROCm tends to lag with kernel support, so this isn't entirely surprising. I moved back to 4.19, but upgrading to 4.19.29, and it's working again (I know that doesn't help you).

**Comment by acowley** [comment]
I think I have things working with kernel 5.0.2 with this [commit](https://github.com/acowley/nixpkgs/commit/7d9d8874f5a842583db5b7fce9deba97dbdb31fe) I pushed to my [hsa_amd](https://github.com/acowley/nixpkgs/tree/hsa_amd) branch of `nixpkgs`.

I will say that I no longer see `amdkfd` in either `dmesg` nor `journalctl` output, so I'm not sure what to do about those as debugging aids. This is all fallout from `amdkfd` being merged into `amdgpu`, but `amdgpu` was being loaded when things weren't working for our kernels, so it's hard to detect when things are working other than running `rocminfo` or similar.

EDIT: Warning: this does require recompiling the kernel which takes a while (at least for me). Please let me know if this works for you so we can work on getting this upstreamed into `nixpkgs` so hydra can build it for us.

**Comment by Wulfsta** [comment]
This can be done using the `extraConfig` section of `boot.kernelPatches`, correct? Something like: 
```
boot.kernelPatches = [  { 
  name = "hsa_amd_enable"; 
  patch = null; 
  extraConfig = ''
    HSA_AMD y
  '';
 }  ];
```

**Comment by acowley** [comment]
I don't know, but that looks reasonable. I would like this to be pulled in to the default kernel configuration in nixpkgs, though. Do you think there's a better of doing that?

**Comment by Wulfsta** [comment]
I tested this last night and it did enable the kfd stuff on my system, but I haven't recompiled with the sandbox paths enabled and tested it yet. I would not call my way of setting the extraconfig the best way to do something like this. Your  nixpkgs change is more elegant, and really the only way to do it if you want to upstream it.

**Comment by Wulfsta** [comment]
I still cannot run either of the commands in the README, though I didn't have any errors in the build. Attempting to run either `rocminfo` or `rom-opencl-runtime` fails with `error: undefined variable 'rocminfo' at (string):1:94` or the analogue for `rocm-opencl-runtime`. This is the same for both my user account and root.

**Comment by acowley** [comment]
If I'm understanding correctly, it sounds like the overlay isn't visible to your user. The README has this unfortunately cryptic note "it may be necessary to link the rocm overlay into ~/.config/nixpkgs/overlays/ so that the rocminfo package is available." It's complicated because there are [various ways](https://nixos.org/nixpkgs/manual/#chap-overlays) to bring overlays into scope. There's the approach we mention in the README of linking distinct overlay files into the `~/.config/nixpkgs/overlays` directory, or one can have a *file* at `~/.config/nixpkgs/overlays.nix`.

**Comment by Wulfsta** [comment]
That was it, I just symlinked the directory to `~/.config/nixpkgs/overlays` and all seems to be working. Thanks for the help!

**Comment by acowley** [comment]
That's wonderful news! I need to update the README and see about a PR to `nixpkgs`.

**Comment by Wulfsta** [comment]
@acowley I have a question that is relevant to this discussion that you might be able to answer. I finally found time to switch to NixOS again, and looking over my `hardware-configuration.nix` realized that `amdgpu` was enabled but not `radeonsi`. Should we be enabling this kernel module as well?

**Comment by acowley** [comment]
@Wulfsta I'm afraid I don't fully understand the relationship between `amdgpu` and `radeonsi`. I do not specifically enable `radeonsi`, and if I ask for it in my `kernelModules`, it doesn't show up in `lsmod` (though `amdgpu` is always there). You see the name `radeonsi` appear in mesa-related backtraces, so it is there, but I don't know exactly what "it" is.

**Comment by Wulfsta** [comment]
@acowley Well, for now I'll leave it enabled. It doesn't seem to be hurting anything at least.
